version: '3.4'

services:
  server:
    build: .
    volumes:
      - .:/server
    ports:
      - 8125:8125
    networks:
      - default
      - networky
  test-client:
    build: .
    volumes:
      - .:/server
    networks:
      - default
      - networky
    command: sleep infinity
networks:
  networky:
    external:
      name: networky
