version: '3.4'

services:
  server:
    build: .
    volumes:
      - .:/server
    environment:
      - "PORT=8124"
    networks:
      - default
  test-client:
    build: .
    volumes:
      - .:/server
    networks:
      - default
    command: sleep infinity
